-- Migrate pro subscriptions to premium
UPDATE public.subscriptions SET plan = 'premium' WHERE plan = 'pro';

-- Wipe all non-trial limits (including any old pro/premium rows) and reseed
DELETE FROM public.plan_feature_limits WHERE plan IN ('basic','standard','premium','pro');

INSERT INTO public.plan_feature_limits (plan, feature_key, limit_value, is_unlimited) VALUES
-- BASIC ($15)
('basic','ai_daily_messages',50,false),
('basic','ai_hourly_fairuse',30,false),
('basic','ai_pricing',100,false),
('basic','ai_followups',50,false),
('basic','ai_calendar',20,false),
('basic','ai_scheduling',0,false),
('basic','ai_voice_assistant',0,false),
('basic','ai_demand_forecasting',0,false),
('basic','ai_conflict_resolution',0,false),
('basic','custom_ai_training',0,false),
('basic','crm_contacts',500,false),
('basic','bookings',50,false),
('basic','industries',1,false),
('basic','basic_analytics',1,false),
('basic','advanced_analytics',0,false),
('basic','calendar_sync',1,false),
('basic','double_booking_protection',1,false),
('basic','email_notifications',1,false),
('basic','deal_pipeline',0,false),
('basic','smart_tasks',0,false),
('basic','lead_scoring',0,false),
('basic','competitor_insights',0,false),
('basic','gap_filling',0,false),
('basic','google_workspace',0,false),
('basic','multi_team',0,false),
('basic','white_label',0,false),

-- STANDARD ($39)
('standard','ai_daily_messages',200,false),
('standard','ai_hourly_fairuse',80,false),
('standard','ai_pricing',500,false),
('standard','ai_followups',300,false),
('standard','ai_calendar',0,true),
('standard','ai_scheduling',0,true),
('standard','ai_voice_assistant',60,false),
('standard','ai_demand_forecasting',0,true),
('standard','ai_conflict_resolution',0,true),
('standard','custom_ai_training',0,false),
('standard','crm_contacts',5000,false),
('standard','bookings',500,false),
('standard','industries',3,false),
('standard','basic_analytics',0,true),
('standard','advanced_analytics',0,true),
('standard','calendar_sync',0,true),
('standard','double_booking_protection',0,true),
('standard','email_notifications',0,true),
('standard','deal_pipeline',1,false),
('standard','smart_tasks',1,false),
('standard','lead_scoring',0,true),
('standard','competitor_insights',0,true),
('standard','gap_filling',0,true),
('standard','google_workspace',1,false),
('standard','multi_team',0,false),
('standard','white_label',0,false),

-- PREMIUM ($99)
('premium','ai_daily_messages',0,true),
('premium','ai_hourly_fairuse',200,false),
('premium','ai_pricing',0,true),
('premium','ai_followups',0,true),
('premium','ai_calendar',0,true),
('premium','ai_scheduling',0,true),
('premium','ai_voice_assistant',500,false),
('premium','ai_demand_forecasting',0,true),
('premium','ai_conflict_resolution',0,true),
('premium','custom_ai_training',1,false),
('premium','crm_contacts',0,true),
('premium','bookings',0,true),
('premium','industries',13,false),
('premium','basic_analytics',0,true),
('premium','advanced_analytics',0,true),
('premium','calendar_sync',0,true),
('premium','double_booking_protection',0,true),
('premium','email_notifications',0,true),
('premium','deal_pipeline',0,true),
('premium','smart_tasks',0,true),
('premium','lead_scoring',0,true),
('premium','competitor_insights',0,true),
('premium','gap_filling',0,true),
('premium','google_workspace',0,true),
('premium','multi_team',1,false),
('premium','white_label',1,false),
('premium','priority_support',1,false);