import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Mail, Sparkles, Loader2, Copy, Send, RefreshCw, Wand2 } from "lucide-react";
import { useCrmContacts } from "@/hooks/useCrm";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";
import type { IndustryType } from "@/lib/industryConfig";

interface Props { industry: IndustryType; preselectedContactId?: string; }

const EMAIL_TONES = [
  { value: "professional", label: "Professional" },
  { value: "friendly", label: "Friendly" },
  { value: "apologetic", label: "Apologetic" },
  { value: "urgent", label: "Urgent" },
  { value: "follow-up", label: "Follow-up" },
  { value: "promotional", label: "Promotional" },
];

const EMAIL_TYPES = [
  { value: "welcome", label: "Welcome Email" },
  { value: "follow-up", label: "Follow-up" },
  { value: "proposal", label: "Proposal" },
  { value: "thank-you", label: "Thank You" },
  { value: "re-engagement", label: "Re-engagement" },
  { value: "upsell", label: "Upsell / Cross-sell" },
  { value: "custom", label: "Custom" },
];

export default function CrmAiEmailComposer({ industry, preselectedContactId }: Props) {
  const { contacts } = useCrmContacts();
  const [selectedContact, setSelectedContact] = useState(preselectedContactId || "");
  const [emailType, setEmailType] = useState("follow-up");
  const [tone, setTone] = useState("professional");
  const [subject, setSubject] = useState("");
  const [body, setBody] = useState("");
  const [customPrompt, setCustomPrompt] = useState("");
  const [loading, setLoading] = useState(false);
  const [generated, setGenerated] = useState(false);

  const generateEmail = async () => {
    setLoading(true);
    try {
      const contact = contacts.find(c => c.id === selectedContact);
      const { data, error } = await supabase.functions.invoke("crm-ai-assistant", {
        body: {
          action: "compose_email",
          data: {
            industry,
            emailType,
            tone,
            customPrompt,
            contact: contact ? {
              name: contact.name, email: contact.email, company: contact.company,
              lifecycle_stage: contact.lifecycle_stage, total_bookings: contact.total_bookings,
              total_revenue: contact.total_revenue, last_contacted_at: contact.last_contacted_at,
            } : null,
          },
        },
      });
      if (error) throw error;
      setSubject(data?.subject || "Follow-up");
      setBody(data?.body || "Could not generate email.");
      setGenerated(true);
      toast.success("Email generated by AI!");
    } catch {
      toast.error("Failed to generate email");
    } finally {
      setLoading(false);
    }
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(`Subject: ${subject}\n\n${body}`);
    toast.success("Email copied to clipboard!");
  };

  return (
    <div className="space-y-4">
      <div className="flex items-center gap-2">
        <Mail className="h-5 w-5 text-primary" />
        <h3 className="text-lg font-semibold">AI Email Composer</h3>
        <Badge variant="secondary" className="text-[10px]">AI-Powered</Badge>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {/* Configuration */}
        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-sm flex items-center gap-2">
              <Wand2 className="h-4 w-4 text-primary" /> Configure Email
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-3">
            <div>
              <label className="text-xs text-muted-foreground mb-1 block">Select Contact (optional)</label>
              <Select value={selectedContact} onValueChange={setSelectedContact}>
                <SelectTrigger><SelectValue placeholder="Choose a contact..." /></SelectTrigger>
                <SelectContent>
                  <SelectItem value="none">No specific contact</SelectItem>
                  {contacts.slice(0, 50).map(c => (
                    <SelectItem key={c.id} value={c.id}>{c.name} {c.email ? `(${c.email})` : ""}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div className="grid grid-cols-2 gap-2">
              <div>
                <label className="text-xs text-muted-foreground mb-1 block">Email Type</label>
                <Select value={emailType} onValueChange={setEmailType}>
                  <SelectTrigger><SelectValue /></SelectTrigger>
                  <SelectContent>
                    {EMAIL_TYPES.map(t => <SelectItem key={t.value} value={t.value}>{t.label}</SelectItem>)}
                  </SelectContent>
                </Select>
              </div>
              <div>
                <label className="text-xs text-muted-foreground mb-1 block">Tone</label>
                <Select value={tone} onValueChange={setTone}>
                  <SelectTrigger><SelectValue /></SelectTrigger>
                  <SelectContent>
                    {EMAIL_TONES.map(t => <SelectItem key={t.value} value={t.value}>{t.label}</SelectItem>)}
                  </SelectContent>
                </Select>
              </div>
            </div>

            <div>
              <label className="text-xs text-muted-foreground mb-1 block">Custom Instructions (optional)</label>
              <Textarea
                placeholder="e.g., Mention our 20% discount on summer bookings..."
                value={customPrompt}
                onChange={e => setCustomPrompt(e.target.value)}
                rows={3}
              />
            </div>

            <Button onClick={generateEmail} disabled={loading} className="w-full">
              {loading ? <><Loader2 className="h-4 w-4 mr-2 animate-spin" />Generating...</> : <><Sparkles className="h-4 w-4 mr-2" />Generate Email</>}
            </Button>
          </CardContent>
        </Card>

        {/* Preview */}
        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-sm flex items-center gap-2">
              <Mail className="h-4 w-4 text-blue-500" /> Email Preview
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-3">
            {generated ? (
              <>
                <div>
                  <label className="text-xs text-muted-foreground mb-1 block">Subject</label>
                  <Input value={subject} onChange={e => setSubject(e.target.value)} />
                </div>
                <div>
                  <label className="text-xs text-muted-foreground mb-1 block">Body</label>
                  <Textarea value={body} onChange={e => setBody(e.target.value)} rows={10} />
                </div>
                <div className="flex gap-2">
                  <Button variant="outline" size="sm" onClick={copyToClipboard}>
                    <Copy className="h-4 w-4 mr-1" /> Copy
                  </Button>
                  <Button variant="outline" size="sm" onClick={generateEmail} disabled={loading}>
                    <RefreshCw className="h-4 w-4 mr-1" /> Regenerate
                  </Button>
                  <Button size="sm" className="ml-auto" onClick={() => toast.info("Email sending coming soon!")}>
                    <Send className="h-4 w-4 mr-1" /> Send
                  </Button>
                </div>
              </>
            ) : (
              <div className="text-center py-12 text-muted-foreground">
                <Mail className="h-12 w-12 mx-auto mb-3 opacity-30" />
                <p className="text-sm">Configure and generate an AI-powered email</p>
                <p className="text-xs mt-1">Select a contact, choose type & tone, then click Generate</p>
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
